### PR TITLE
Torch DeepSpeech2 Benchmark multi-GPU

### PR DESCRIPTION
**Pull request by SeanNaren**
Hey I've added multi-GPU support to the torch benchmark, hopefully it's useful. Let me know of any issues/feedback on the PR!

EDIT: should've also added I think we need some form of progress monitoring, because running the benchmark is a lengthy process (through the entire dataset). xlua alright for this?

### CODE REVIEW

**Comment by SeanNaren** [comment]
Thought I could sneak in a progress bar to the PR! @soumith currently it gives the same stats as the covnet benchmarks, do we want anything else (total time taken or something)?

**Comment by soumith** [comment]
ok this is cool. just need a stats reporting like:
epoch time, total number of samples processed. samples / second.
And some metric that reports a (normalized sample length) / second

**Comment by SeanNaren** [comment]
@soumith what do you mean (normalized sample length) / second?

**Comment by soumith** [comment]
The data samples are of different utterance lengths each. We want a metric that gives the throughput. So, [(seconds of audio processed) / second] for example would be a normalized metric

**Comment by SeanNaren** [comment]
Hopefully the added measurements are correct, here is a table including all the current headers

| Hardware | Time (ms) | forward (ms) | backward (ms) | Samples processed | Samples processed per second | Seconds of audio processed per second | Epoch time (s) |
| :-: | --: | --: | --: | --: | --: | --: | --: |
| 1x Titans | - | - | - | - | - | - | - |
| 4x Titans | - | - | - | - | - | - | - |

Does this cover everything needed? Let me know if anything needs changing etc.

EDIT: 5 runs enough for the average?

**Comment by soumith** [comment]
Thanks a ton Sean!

**Pull request merged**
